version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_bd
    ports:
      - "5432:5432"
  hasura:
    image: hasura/graphql-engine:v2.0.10
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgresql://root:root@database:5432/test_bd
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
